function an = OPC_NBSS_Plot_Legend(OPC,txt)


if nargin == 1
    txt = 10;
end


try
an = eval(['annotation(''textbox'', [.15 .15 .25 .25], ''String'','...
            '{''\bfOPC NBSS: Linear Fitting\rm'...
            '''; ''Slope = ',num2str(roundn(OPC.NBSS.Lin.Slope,-2)),''...
            '''; ''Intercept = ',num2str(roundn(OPC.NBSS.Lin.Intercept,-2)),''...
            '''; ''r^2 = ',num2str(roundn(OPC.NBSS.Lin.r2,-2)),''...
            '''; '''...
            '''; ''Biomass = ',num2str(ceil(OPC.Stats.Biomass)),' mg m^{-3}'...
            '''; ''Abundance = ',num2str(round(OPC.Stats.Abundance)),' m^{-3}'...
            '''},''background'',''w'',''interpreter'',''tex'',''fontsize'',',num2str(txt),');']);

        %             '''; ''\bfOPC NBSS: Non-Linear Fitting\rm'...
%             '''; ''Y-vertex co-ord = ',num2str(roundn(OPC.NBSS.NLin.mdl.feval(log10(OPC.NBSS.Bins(1))),-1)),' m^{-3}'...
%             '''; ''Curvature = ',num2str(roundn(OPC.NBSS.NLin.Curve,-1)),''...
%             '''; '''...
        
        
catch
    an = eval(['annotation(''textbox'', [.15 .15 .25 .25], ''String'','...
            '{''\bfOPC NBSS: Linear Fitting\rm'...
            '''; ''Slope = ',num2str(roundn(OPC.NBSS.Lin.Slope,-2)),''...
            '''; ''Intercept = ',num2str(roundn(OPC.NBSS.Lin.Intercept,-2)),''...
            '''; '''...
            '''; ''Biomass = ',num2str(ceil(OPC.Stats.Biomass)),' mg m^{-3}'...
            '''; ''Abundance = ',num2str(round(OPC.Stats.Abundance)),' m^{-3}'...
            '''},''background'',''w'',''interpreter'',''tex'',''fontsize'',',num2str(txt),');']);
end


%             '''; ''\bfOPC NBSS: Non-Linear Fitting\rm'...
%             '''; ''Y-vertex co-ord = NaN m^{-3}'...
%             '''; ''Curvature = ',num2str(roundn(OPC.NBSS.NLin.Curve,-1)),''...
%             '''; '''...



%      set(an,'parent',gca);
%      set(an,'position',[.05 .05 .32 .32]);

